# Generated by Django 5.2.6 on 2025-09-16 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('stars', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('watchers', models.IntegerField()),
                ('is_fork', models.BooleanField()),
                ('is_archived', models.BooleanField()),
                ('languages', models.JSONField()),
                ('language_count', models.IntegerField()),
                ('topics', models.JSONField()),
                ('topic_count', models.IntegerField()),
                ('disk_usage_kb', models.IntegerField()),
                ('pull_requests', models.IntegerField()),
                ('issues', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('default_branch_commit_count', models.IntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('assignable_user_count', models.IntegerField()),
                ('code_of_conduct', models.CharField(blank=True, max_length=100, null=True)),
                ('forking_allowed', models.BooleanField()),
                ('name_with_owner', models.CharField(max_length=200, unique=True)),
                ('parent', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField()),
                ('year', models.IntegerField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_languages', to='reportapp.githubrepository')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_usages', to='reportapp.languagename')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'language'], name='reportapp_g_year_81b245_idx')],
            },
        ),
    ]
