# Generated by Django 5.2.6 on 2025-09-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='githublanguage',
            index=models.Index(fields=['year'], name='reportapp_g_year_6e1755_idx'),
        ),
        migrations.AddIndex(
            model_name='githublanguage',
            index=models.Index(fields=['language'], name='reportapp_g_languag_e2c1f0_idx'),
        ),
    ]
