# Generated by Django 5.2.6 on 2025-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='githublanguage',
            index=models.Index(fields=['year', 'name'], name='reportapp_g_year_07442f_idx'),
        ),
    ]
